name: CI

on:
  workflow_dispatch:

jobs:
  sign:
    runs-on: macos-12
    timeout-minutes: 30
    env:
      SECRET_URL: "${{ secrets.SECRET_URL }}"
      SECRET_KEY: "${{ secrets.SECRET_KEY }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Sign
        run: |
          PYTHONUNBUFFERED=1 ./sign.py
